version: "3.9"
services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./project/:/app/
      - ./project/data/web:/vol/web
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=dev_key
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme