# Generated by Django 2.2.24 on 2021-08-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('property', 'schedule')},
        ),
    ]
